name: Staging deployment

on:
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: nicolas-sanch-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: nicolas-sanch-ttt-app
  #################################################
    
jobs:
  build:
    runs-on: ubuntu-latest
